### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by jrperdomoz** [csuft/iVirtualCamera#2]
I need uninstall this software.  What is the process?

My Mac restarts continuously with this error.

Sun Jan 28 15:28:50 2018

*** Panic Report ***
panic(cpu 2 caller 0xffffff802b86627c): "IOVideoSampleDevice[0x10000027b]::terminate(kIOServiceSynchronous) timeout\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4570.31.3/iokit/Kernel/IOService.cpp:2289
Backtrace (CPU 2), Frame : Return Address
0xffffff821813b830 : 0xffffff802b2505f6 
0xffffff821813b880 : 0xffffff802b37d604 
0xffffff821813b8c0 : 0xffffff802b36f0f9 
0xffffff821813b940 : 0xffffff802b202120 
0xffffff821813b960 : 0xffffff802b25002c 
0xffffff821813ba90 : 0xffffff802b24fdac 
0xffffff821813baf0 : 0xffffff802b86627c 
0xffffff821813bb40 : 0xffffff802b869d27 
0xffffff821813bbc0 : 0xffffff802b889561 
0xffffff821813bbf0 : 0xffffff802b889755 
0xffffff821813bc30 : 0xffffff802b81ec51 
0xffffff821813bc70 : 0xffffff802b824f25 
0xffffff821813bcf0 : 0xffffff802b833c5e 
0xffffff821813bd60 : 0xffffff802b2a59b7 
0xffffff821813bdc0 : 0xffffff802b255c30 
0xffffff821813be10 : 0xffffff802b232cbd 
0xffffff821813be60 : 0xffffff802b245b7b 
0xffffff821813bef0 : 0xffffff802b35952d 
0xffffff821813bfa0 : 0xffffff802b202926 

BSD process name corresponding to current thread: kextunload

Mac OS version:
17C88

Kernel version:
Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
Kernel UUID: 87641697-A3DD-30C4-B010-E65ECE57550B
Kernel slide:     0x000000002ae00000
Kernel text base: 0xffffff802b000000
__HIB  text base: 0xffffff802af00000
System model name: MacBookPro9,2 (Mac-6F01561E16C75D06)

System uptime in nanoseconds: 147325983103
last loaded kext at 61672229410: org.virtualbox.kext.VBoxNetAdp	5.1.28 (addr 0xffffff7fae56f000, size 28672)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	5.1.28
org.virtualbox.kext.VBoxNetFlt	5.1.28
org.virtualbox.kext.VBoxUSB	5.1.28
org.virtualbox.kext.VBoxDrv	5.1.28
com.displaylink.driver.DisplayLinkDriver	3.1.0 (82262)
com.insta360.cmio.driver.Sample	1.0.0d1
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AGPM	110.23.24
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.filesystems.autofs	3.0
com.apple.driver.AppleMikeyHIDDriver	131
com.apple.driver.AppleGraphicsDevicePolicy	3.16.21
com.apple.AGDCPluginDisplayMetrics	3.16.2
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.driver.AppleHDAHardwareConfigDriver	280.12
com.apple.iokit.IOBluetoothSerialManager	6.0.2f2
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHDA	280.12
com.apple.driver.AppleMikeyDriver	280.12
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelHD4000Graphics	10.3.0
com.apple.driver.AppleMuxControl	3.16.21
com.apple.driver.AppleThunderboltIP	3.1.1
com.apple.driver.eficheck	1
com.apple.driver.AppleSMCPDRC	1.0.0
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleSMCLMU	211
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AGDCBacklightControl	3.16.2
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelFramebufferCapri	10.3.0
com.apple.driver.AppleBacklight	170.10.2
com.apple.driver.AppleMCCSControl	1.5.3
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.iokit.IOBluetoothUSBDFU	6.0.2f2
com.apple.driver.AppleUSBTCKeyEventDriver	254
com.apple.driver.AppleUSBTCButtons	254
com.apple.driver.AppleUSBTCKeyboard	254
com.apple.driver.AppleIRController	352
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	40
com.apple.filesystems.hfs.kext	407.30.1
com.apple.iokit.SCSITaskUserClient	404.30.2
com.apple.iokit.AppleBCM5701Ethernet	10.3.1
com.apple.driver.AppleAHCIPort	329
com.apple.driver.AppleSDXC	1.7.6
com.apple.driver.AppleFWOHCI	5.5.8
com.apple.driver.AirPort.Brcm4331	800.21.30
com.apple.driver.AirPort.Brcm4360	1220.18.1a2
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.driver.AppleIntelCPUPowerManagementClient	220.0.0
com.apple.nke.applicationfirewall	183
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.driver.AppleIntelCPUPowerManagement	220.0.0
com.apple.IOBufferCopyEngineTest	1
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleSSE	1.0
com.apple.driver.DspFuncLib	280.12
com.apple.kext.OSvKernDSPLib	526
com.apple.driver.AppleGraphicsControl	3.16.21
com.apple.iokit.IOFireWireIP	2.2.8
com.apple.AppleGPUWrangler	3.16.2
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.driver.AppleThunderboltEDMSink	4.1.2
com.apple.driver.AppleThunderboltDPOutAdapter	5.0.2
com.apple.iokit.IOAcceleratorFamily2	376.6
com.apple.iokit.IOSurface	209.2.2
com.apple.AppleGraphicsDeviceControl	3.16.21
com.apple.driver.AppleHDAController	280.12
com.apple.iokit.IOHDAFamily	280.12
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	517.22
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.iokit.IOGraphicsFamily	517.22
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerUSBTransport	6.0.2f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.2f2
com.apple.iokit.IOBluetoothFamily	6.0.2f2
com.apple.driver.AppleUSBMultitouch	261
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.usb.AppleUSBHub	1.2
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOVideoFamily	1.2.1
com.apple.iokit.IOStreamFamily	1.1.0
com.apple.iokit.IOSCSIMultimediaCommandsDevice	404.30.2
com.apple.iokit.IOBDStorageFamily	1.8
com.apple.iokit.IODVDStorageFamily	1.8
com.apple.iokit.IOCDStorageFamily	1.8
com.apple.driver.AppleThunderboltDPInAdapter	5.0.2
com.apple.driver.AppleThunderboltDPAdapterFamily	5.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.3
com.apple.driver.AppleXsanScheme	3
com.apple.iokit.IOAHCISerialATAPI	267
com.apple.iokit.IOAHCIBlockStorage	301.20.1
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleThunderboltNHI	4.5.6
com.apple.iokit.IOThunderboltFamily	6.6.3
com.apple.iokit.IOAHCIFamily	288
com.apple.iokit.IOFireWireFamily	4.6.8
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleUSBMergeNub	900.4.1
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBEHCIPCI	1.2
com.apple.driver.usb.AppleUSBEHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	439.30.4
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.iokit.IOUSBMassStorageDriver	140.30.1
com.apple.iokit.IOSCSIBlockCommandsDevice	404.30.2
com.apple.iokit.IOSCSIArchitectureModelFamily	404.30.2
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOBufferCopyEngineFamily	1
com.apple.driver.DiskImages	480.30.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOTimeSyncFamily	650.5
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMCRTC	1.0
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0

EOF
Model: MacBookPro9,2, BootROM MBP91.00D7.B00, 2 processors, Intel Core i7, 2.9 GHz, 16 GB, SMC 2.2f41
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453220
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453220
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.16.1a2)
Bluetooth: Version 6.0.2f2, 3 services, 18 devices, 0 incoming serial ports
Serial ATA Device: SanDisk SDSSDA240G, 240.06 GB
Serial ATA Device: HL-DT-ST DVDRW  GS41N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 3.0 Bus
USB Device: ASMT1153e
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by jrperdomoz** [comment]
I have reinstalled the operating system....

**Comment by MidoFX** [comment]
Here's the steps for anyone who wants to uninstall this thing

Go go: **HD\Library\CoreMediaIO\Plug-Ins\DAL**

Then "**Delete**" **Insta360VCam.plugin** & WirecastVirtualCamera.plugin if it's there.

Enter your admin password then you good to go

![screen shot 2018-07-22 at 3 25 09 am](https://user-images.githubusercontent.com/39290891/43044663-53ede5a2-8d5f-11e8-9c67-510cb1b08b52.jpg)

![screen shot 2018-07-22 at 3 24 55 am](https://user-images.githubusercontent.com/39290891/43044664-5c6d1e14-8d5f-11e8-8b9a-2732c2638450.jpg)
